/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 Grill.glb --transform 
Files: Grill.glb [5.02KB] > E:\Codeprojects\ShawermaShopNameGenerator\public\Grill-transformed.glb [2.03KB] (60%)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Grill-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Grill.geometry} material={materials.GrillMaterial} />
    </group>
  )
}

useGLTF.preload('/Grill-transformed.glb')
